name: Deployimg Lambda Function

on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: setup python
        uses : actions/setup-python@v2
      - name: install libraries
        run: |
          cd functions
          pip install -r requirements.txt -t
      - name: create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:  
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
  
